### ISSUE TITLE
MSInteger32.update() method doesn't work

### ISSUE THREAD

**Issue by ghost** [teromene/kac-editor#1]
Hellow,

I encountered an issue using your package to manipulate my Kingdoms and Castles Savestates. The problem is located on the MSInteger32 class, because I'm not able to manipulate integer32 values using the respective [`update()` method](https://github.com/teromene/kac-editor/blob/master/vartypes.py#L30). I'm really not into Byte handling at all, but after 2 hours and a few websites I guess I found a solution... At least it worked on my case:

My updated `update()` method (on the MSInteger32 class) uses the little endian (?) "<I" version on the `struct.pack` function and moves all 4 bytes to the respective positions on the given `dataArray` variable.

```python
def update(self, dataArray, value):
    v = struct.pack("<I", value)
    dataArray[self.position]     = v[0];
    dataArray[self.position + 1] = v[1];
    dataArray[self.position + 2] = v[2];
    dataArray[self.position + 3] = v[3];
    self.value = value
```
A fantastic way to test this out is by updating the gold counter... (Which is just for testing purposes, of course... Everything else would be cheating...)

```python
objects, dataFile = extractor.parseSaveFile( pathtoSaveState )
objects["LandmassOwner+LandmassOwnerSaveData"]["gold"].update( dataFile, 42 )
extractor.writeSaveFile( pathtoSaveState, dataFile )
```

Thanks for your work!

Sincerely,
Sam.

**Comment by teromene** [comment]
Thanks for the info ! I have pushed your solution upstream
